'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowDown,ArrowUpRight,Play,Pause,RotateCcw,X} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
type Project={id:string;title:string;category:string;story:string;file:string;portrait?:boolean;source?:string;alternatives?:{label:string;file:string}[]};
const projects:Project[]=[
{id:'01-kupino',title:'Маленькие герои. Большой мир.',category:'Купиночки · бренд-анимация',story:'Первая серия истории для «Купинского»: мир сладостей, характеры героев и приключение, которое продолжается за пределами одного ролика.',file:'kupino.mp4',portrait:true},
{id:'02-clip',title:'Стоп, террорист',category:'Лия Волянская · музыкальный клип',story:'Ночной город, сценические образы и сюжетные эпизоды в музыкальном клипе Лии Волянской. Работа опубликована на сайте Национального антитеррористического комитета.',file:'clip.mp4',source:'https://nac.gov.ru/list/categoryId/65/view/019edb41-0e67-7351-a078-a141b1bd77b9'},
{id:'03-food',title:'История начинается на кухне',category:'Пельмени · реклама',story:'Маленький бегемот, семейное утро и продукт в центре истории. Анимационная реклама пельменей «Весёлые зверюшки».',file:'food.mp4'},
{id:'04-product',title:'Один продукт. Два настроения.',category:'Зарядное устройство · реклама',story:'Повседневная обстановка и выразительный образ с контрастным светом. Два подхода к рекламе одного устройства.',file:'product.mp4',portrait:true,alternatives:[{label:'Повседневная история',file:'product.mp4'},{label:'Контрастный образ',file:'fashion.mp4'}]},
{id:'05-auto',title:'За пределами съёмочной площадки',category:'Автомобили · визуальные концепты',story:'Световой каркас становится автомобилем, камера исследует интерьер, дорога меняет окружение. Визуальные концепты; сотрудничество с автомобильными брендами не заявляется.',file:'auto-light.mp4',alternatives:[{label:'Световой каркас',file:'auto-light.mp4'},{label:'В дороге',file:'auto-road.mp4'},{label:'Интерьер',file:'auto-interior.mp4'},{label:'Тоннель',file:'auto-tunnel.mp4'}]},
{id:'06-love-story',title:'Помнишь, как всё началось?',category:'Love story · личная история',story:'Знакомство, свидания, путешествия и маленькие моменты, которые становятся общей историей. Личный анимационный фильм про пару.',file:'love.mp4',portrait:true},
{id:'07-marina',title:'Марина. История, в которой свои.',category:'Семья · персональный фильм',story:'Семья, взросление, учёба, путешествия и любовь. Анимационный фильм про Марину и людей рядом с ней.',file:'marina.mp4'},
{id:'08-clinic',title:'Команда становится героями',category:'Медицинский центр · анимация',story:'Люди, кабинеты и повседневная работа медицинского центра в анимационной истории. Формат, который помогает показать компанию через её команду.',file:'clinic.mp4'},
{id:'09-transformation',title:'Тот же жест. Другой образ.',category:'Перевоплощение · до / после',story:'Исходное видео и цифровое перевоплощение в образ Мэрилин Монро рядом. Меняются лицо, причёска, одежда и окружение, при этом сохраняется связь с жестами исходной героини.',file:'transformation.mp4'}];
function Preview({p}:{p:Project}){const ref=useRef<HTMLVideoElement>(null);return <div className={`case-visual ${p.portrait?'portrait':''}`} onPointerEnter={()=>{const v=ref.current;if(v&&!matchMedia('(prefers-reduced-motion: reduce)').matches){if(!v.src)v.src=`/media/previews/${p.id}.mp4`;void v.play().catch(()=>{});}}} onPointerLeave={()=>ref.current?.pause()}><img src={`/media/previews/${p.id}.jpg`} alt="" loading="lazy" width="1280" height="960"/><video ref={ref} muted loop playsInline preload="none" aria-hidden="true"/><span className="play-disc"><Play size={22} fill="currentColor"/></span><span className="case-note">Смотреть работу</span></div>}
export default function Home(){const[selected,setSelected]=useState<Project|null>(null);const[activeFile,setActiveFile]=useState('');const[reel,setReel]=useState(false);const[motion,setMotion]=useState(true);const[jump,setJump]=useState(0);const reelRef=useRef<HTMLVideoElement>(null);
useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)setMotion(false);},[]);
useEffect(()=>{const el=reelRef.current;if(!el)return;const o=new IntersectionObserver(([e])=>{if(e.isIntersecting&&motion){if(!el.src)el.src='/media/showreel-web.mp4';void el.play().catch(()=>{});}else el.pause();},{threshold:.15});o.observe(el);return()=>o.disconnect();},[motion]);
function open(p:Project){setSelected(p);setActiveFile(p.file)}
return <main className={motion?'motion-on':'motion-off'}><a className="skip-link" href="#work">Перейти к работам</a>
<header className="header"><a href="#" className="brand" aria-label="M&M — на главную">M<span>&</span>M</a><nav aria-label="Навигация"><a href="#work">Работы</a><a href="#studio">Два Миши</a><a href="#contact" className="nav-contact">Обсудить идею <ArrowUpRight size={16}/></a></nav></header>
<section className="hero"><div className="hero-top"><p className="eyebrow"><i/>НЕЗАВИСИМАЯ ВИДЕОСТУДИЯ</p><p className="hero-index">ИДЕЯ → КАДР → ЭМОЦИЯ</p></div><h1>Два Миши.<br/><span>Много историй.</span></h1>
<div className="letter-stage" key={jump}><svg className="lamp-stage" viewBox="0 0 1000 490" role="img" aria-label="Шарнирная настольная лампа прыгает по буквам M&M">
<defs><linearGradient id="metal" x1="0" y1="0" x2="1" y2="1"><stop stopColor="#faf9ee"/><stop offset=".45" stopColor="#b9c1c0"/><stop offset=".7" stopColor="#727d80"/><stop offset="1" stopColor="#e7ece6"/></linearGradient><radialGradient id="bulb"><stop stopColor="#fffef0"/><stop offset=".6" stopColor="#fff5bc"/><stop offset="1" stopColor="#d8ec8c"/></radialGradient><linearGradient id="beam" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#eaffb1" stopOpacity=".3"/><stop offset="1" stopColor="#d9fa69" stopOpacity="0"/></linearGradient></defs>
<g className="lamp-letters" aria-hidden="true"><text className="lamp-letter-left" x="125" y="462">M</text><text className="lamp-amp" x="465" y="462">&amp;</text><text className="lamp-letter-right" x="665" y="462">M</text></g>
<g transform="translate(270 210)"><g className="lamp-travel"><ellipse className="lamp-shadow" cy="7" rx="52" ry="7" fill="#d9fa69" opacity=".2"/><g className="lamp-body"><path className="lamp-beam" d="M23 -144 L-28 4 L168 4 L58 -151Z" fill="url(#beam)"/>
<ellipse cy="-3" rx="44" ry="8" fill="#394446"/><path d="M-43 -5 Q-35 -16 -8 -15 L-5 -28 L6 -28 L9 -15 Q35 -14 43 -5 Q0 3 -43 -5Z" fill="url(#metal)" stroke="#647073" strokeWidth="2"/>
<g fill="none" stroke="url(#metal)" strokeWidth="7" strokeLinejoin="round"><path d="M0 -24 L-35 -68 L-2 -119 L13 -112 L-17 -66 L10 -30Z"/><path d="M-29 -70 L-12 -65 M-25 -79 L-8 -74" strokeWidth="2"/></g><g fill="#cbd2cd" stroke="#586467" strokeWidth="3"><circle cy="-29" r="6"/><circle cx="-27" cy="-68" r="7"/><circle cx="5" cy="-115" r="6"/></g>
<g className="lamp-head"><path d="M3 -119 L16 -140" stroke="#b8c1bd" strokeWidth="8"/><path d="M9 -147 Q0 -178 25 -183 L64 -153 L43 -119Z" fill="url(#metal)" stroke="#738082" strokeWidth="2"/><ellipse cx="51" cy="-147" rx="22" ry="34" transform="rotate(32 51 -147)" fill="url(#bulb)" stroke="#e9ecdc" strokeWidth="5"/><ellipse cx="51" cy="-147" rx="10" ry="15" transform="rotate(32 51 -147)" fill="#fffef1"/></g></g></g></g>
</svg><span className="stage-caption">ВООБРАЖЕНИЕ В ДВИЖЕНИИ</span></div>
<div className="hero-bottom"><p>Создаём рекламу, клипы и анимационные<br/>истории, которые хочется пересмотреть.</p><button className="pill primary" onClick={()=>setReel(true)}><Play size={16} fill="currentColor"/>Смотреть шоурил <span>00:32</span></button><div className="motion-controls"><button onClick={()=>setJump(j=>j+1)} aria-label="Повторить заставку"><RotateCcw size={17}/></button><button onClick={()=>setMotion(!motion)} aria-label={motion?'Остановить анимацию':'Включить анимацию'}>{motion?<Pause size={17}/>:<Play size={17}/>}</button></div></div><a href="#work" className="scroll-cue">ЛИСТАЙТЕ, ТУТ ИНТЕРЕСНО <ArrowDown size={16}/></a></section>
<section className="reel-section" aria-label="Подборка работ"><button className="reel-frame" onClick={()=>setReel(true)} aria-label="Посмотреть шоурил со звуком"><video ref={reelRef} muted loop playsInline preload="none" poster="/media/reel-poster.jpg"/><span className="reel-label">M&M / SELECTED WORK</span><span className="reel-play"><Play size={28} fill="currentColor"/><span>Включить звук</span></span></button></section>
<section id="work" className="work-section"><div className="section-heading"><div><p className="eyebrow">01 / ИЗБРАННОЕ</p><h2>Смотрите,<br/><em>что возможно.</em></h2></div><p>От мира мороженого до ночного города.<br/>У каждой идеи — свой язык.</p></div><div className="projects-grid">{projects.map((p,i)=><article key={p.id} className={`project project-${i+1}`}><button className="project-open" onClick={()=>open(p)} aria-label={`Смотреть: ${p.title}`}><Preview p={p}/><div className="case-meta"><span>{p.category}</span><ArrowUpRight size={22}/></div><h3>{p.title}</h3></button></article>)}</div></section>
<section id="studio" className="studio-section"><div className="studio-heading"><p className="eyebrow">02 / ЗА КАДРОМ</p><h2>За каждым «вау»<br/>стоят <em>люди.</em></h2><p>Мы — Миша Гантимуров и Миша Останин.<br/>Вместе с командой превращаем идеи в видео: от рекламы продукта до личной истории.</p></div><div className="founders"><article><div className="founder-portrait portrait-gantimurov"><img src="/images/gantimurov-photo.jpg" alt="Миша Гантимуров в студии" loading="lazy" width="960" height="1280"/></div><h3>Миша Гантимуров</h3><a href="https://t.me/Sigar_Boss" target="_blank" rel="noreferrer">@Sigar_Boss <ArrowUpRight size={16}/></a></article><article><div className="founder-portrait portrait-ostanin"><img src="/images/ostanin-photo.jpg" alt="Миша Останин" loading="lazy" width="960" height="1280"/></div><h3>Миша Останин</h3><a href="https://t.me/MihailOstanin2" target="_blank" rel="noreferrer">@MihailOstanin2 <ArrowUpRight size={16}/></a></article></div></section>
<section id="contact" className="contact-section"><p className="eyebrow">03 / ВАША СЛЕДУЮЩАЯ ИСТОРИЯ</p><h2>Есть идея?<br/><span>Давайте в кадр.</span><ArrowUpRight aria-hidden="true"/></h2><div className="contact-bottom"><p>Пришлите идею, задачу или референс.<br/>Обсудим, каким может быть ваш ролик.</p><div className="contact-person"><span>МИША ГАНТИМУРОВ</span><a href="https://t.me/Sigar_Boss" target="_blank" rel="noreferrer">Написать в Telegram <ArrowUpRight size={18}/></a><a href="tel:+79958830978">+7 995 883-09-78</a></div><div className="contact-person"><span>МИША ОСТАНИН</span><a href="https://t.me/MihailOstanin2" target="_blank" rel="noreferrer">Написать в Telegram <ArrowUpRight size={18}/></a><a href="tel:+79969590470">+7 996 959-04-70</a></div></div></section>
<footer><a href="#" className="brand">M<span>&</span>M</a><span>Реклама. Клипы. Анимация.</span><span>© M&M, 2026</span><a href="#">Наверх ↑</a></footer>
<Dialog open={Boolean(selected)||reel} onOpenChange={o=>{if(!o){setSelected(null);setReel(false)}}}><DialogContent className="film-dialog" showCloseButton={false}><div className="film-heading"><div><DialogTitle className="film-title">{reel?'M&M / Шоурил':selected?.title}</DialogTitle><DialogDescription className="film-description">{reel?'Реклама, клипы и анимационные истории. 32 секунды.':selected?.category}</DialogDescription></div><DialogClose className="close-film" aria-label="Закрыть видео"><X size={24}/></DialogClose></div>{(selected||reel)&&<video key={reel?'reel':activeFile} src={reel?'/media/showreel.mp4':`/media/full/${activeFile}`} controls autoPlay playsInline preload="metadata" className="film-player"/>}{selected?.alternatives&&<div className="film-alternatives">{selected.alternatives.map(a=><button key={a.file} className={a.file===activeFile?'active':''} onClick={()=>setActiveFile(a.file)}>{a.label}</button>)}</div>}{selected&&<p className="film-story">{selected.story}</p>}{selected?.source&&<div className="source-links"><a href={selected.source} target="_blank" rel="noreferrer">Публикация на сайте НАК <ArrowUpRight size={15}/></a><a href="https://vkvideo.ru/video-189986775_456244001" target="_blank" rel="noreferrer">Смотреть на VK Видео <ArrowUpRight size={15}/></a></div>}</DialogContent></Dialog></main>}
